const branchData = {
    'chibo1': {
        title: '<i class="fa-solid fa-users"></i> Danh sách Đảng viên - Chi bộ 1',
        members: [
            { name: 'Đ/c Phạm Chí Thiện', role: 'Bí thư Đảng ủy/Chủ tịch HĐQT', term: '2025 - 2027', avatar: 'Thiện', color: 'var(--party-red)', roleColor: 'var(--party-red)', avatarBg: 'da3633' },
            { name: 'Đ/c Phan Kim Phượng', role: 'Trưởng Ban kiểm soát', term: '2025 - 2027', avatar: 'Phượng', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Đặng Minh Hùng', role: 'Bí thư Chi bộ 1 Trưởng phòng Tổ chức -Hành chính', term: '2025 - 2027', avatar: 'Hùng', color: 'var(--party-red)', roleColor: 'var(--party-red)', avatarBg: 'da3633' },
            { name: 'Đ/c Trần Đức Hùng', role: 'ĐUV, Phó Bí thư Chi bộ 1 Kế Toán trưởng', term: '2025 - 2027', avatar: 'Hùng', color: 'var(--party-red)', roleColor: 'var(--party-red)', avatarBg: 'da3633' },
            { name: 'Đ/c Võ Thị Hồng Hà', role: 'Chuyên gia', term: '2025 - 2027', avatar: 'Hà', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Thanh Tâm', role: 'ĐUV, Phó Trưởng Phòng TC-HC', term: '2025 - 2027', avatar: 'Tâm', color: 'transparent', roleColor: 'var(--status-info)', avatarBg: '2f81f7' },
            { name: 'Đ/c Lê Thanh Lâm', role: 'Phòng Tổ chức - Hành chính', term: '2025 - 2027', avatar: 'Lâm', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Phan Thị Hồng Cẩm', role: 'Phó Trưởng Phòng Tổ chức - Hành chính', term: '2025 - 2027', avatar: 'Cẩm', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Huỳnh Thị Thúy Diễm', role: 'Chi ủy viên chi bộ 1 Phòng Tổ chức - Hành chính', term: '2025 - 2027', avatar: 'Diễm', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Mai Thị Thúy Hằng', role: 'Phòng Tổ chức - Hành chính', term: '2025 - 2027', avatar: 'Hằng', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Phạm Ngọc Nhật Thanh', role: 'Phòng Tổ chức - Hành chính', term: '2025 - 2027', avatar: 'Thanh', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Đỗ Hoàng Nhung', role: 'Phòng Tổ chức - Hành chính', term: '2025 - 2027', avatar: 'Nhung', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Thị Tường', role: 'Phòng Tổ chức - Hành chính', term: '2025 - 2027', avatar: 'Tường', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Thị Hồng Duyên', role: 'Phó Trưởng Phòng Kế toán tài chính', term: '2025 - 2027', avatar: 'Duyên', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Chu Mạnh Tuấn', role: 'Phòng Kế toán tài chính', term: '2025 - 2027', avatar: 'Tuấn', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Lê Anh Thư', role: 'Phòng Kế toán tài chính', term: '2025 - 2027', avatar: 'Thư', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
        ]
    },
    'chibo2': {
        title: '<i class="fa-solid fa-users"></i> Danh sách Đảng viên - Chi bộ 2',
        members: [
            { name: 'Đ/c Lê Trọng Hiếu', role: 'Phó Bí thư đảng ủy, Giám đốc', term: '2025 - 2027', avatar: 'Hiếu', color: 'var(--party-red)', roleColor: 'var(--party-red)', avatarBg: 'da3633' },
            { name: 'Đ/c Trần Duy Minh', role: 'ĐUV, Bí thư Chi bộ 2 Trưởng Phòng Kỹ thuật', term: '2025 - 2027', avatar: 'Minh', color: 'var(--party-red)', roleColor: 'var(--party-red)', avatarBg: 'da3633' },
            { name: 'Đ/c Nguyễn Thị Kim Yến', role: 'Phó Bí Thư Chi bộ 2 Phó Trưởng Phòng Kỹ thuật', term: '2025 - 2027', avatar: 'Yến', color: 'var(--party-red)', roleColor: 'var(--party-red)', avatarBg: 'da3633' },
            { name: 'Đ/c Phạm Nguyễn Tuấn Anh', role: 'Phó Trưởng Phòng Kỹ thuật', term: '2025 - 2027', avatar: 'Anh', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Trương Thanh Tòng', role: 'Phòng Kỹ thuật', term: '2025 - 2027', avatar: 'Tòng', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Đỗ Trung Ninh', role: 'Phòng Kỹ thuật', term: '2025 - 2027', avatar: 'Ninh', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Đoàn Thị Thảo Ngân', role: 'Phòng Kỹ thuật', term: '2025 - 2027', avatar: 'Ngân', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Lê Đức Phú', role: 'Phòng Kỹ thuật', term: '2025 - 2027', avatar: 'Phú', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Đức Hiếu', role: 'Phòng Kỹ thuật', term: '2025 - 2027', avatar: 'Hiếu', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Quách Tuấn Ngọc', role: 'Phòng Kỹ thuật', term: '2025 - 2027', avatar: 'Ngọc', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Bảo Trung', role: 'Phòng Kỹ thuật', term: '2025 - 2027', avatar: 'Trung', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Hà Đắc Lộc', role: 'Phòng Kỹ thuật', term: '2025 - 2027', avatar: 'Lộc', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Phan Minh Đoàn', role: 'Bí thư Đoàn thanh niên, Phòng kỹ thuật', term: '2025 - 2027', avatar: 'Đoàn', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Chu Mạnh Hùng', role: 'Phòng Kỹ thuật', term: '2025 - 2027', avatar: 'Hùng', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Phạm Đức Huy', role: 'Phòng Kỹ thuật', term: '2025 - 2027', avatar: 'Huy', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Đinh Thị Đằng Hương', role: 'Phó Trưởng Phòng Kế hoạch vật tư', term: '2025 - 2027', avatar: 'Hương', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Thanh Thụy An', role: 'Phó Trưởng Phòng Kế hoạch vật tư', term: '2025 - 2027', avatar: 'An', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Đặng Hồ Thanh Lý', role: 'Phòng Kế hoạch vật tư', term: '2025 - 2027', avatar: 'Lý', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Đặng Hậu', role: 'Phòng Kế hoạch vật tư', term: '2025 - 2027', avatar: 'Hậu', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Dương Thị Ngọc Hân', role: 'Chi ủy viên chi bộ 2 Trưởng Phòng CNTT', term: '2025 - 2027', avatar: 'Hân', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Thị Thanh Phương', role: 'Trưởng Ban Quản lý dự án', term: '2025 - 2027', avatar: 'Phương', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Thị Lệ', role: 'Ban Quản lý dự án', term: '2025 - 2027', avatar: 'Lệ', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Quốc Phong', role: 'Phó Trưởng Ban Quản lý dự án', term: '2025 - 2027', avatar: 'Phong', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
        ]
    },
    'chibo3': {
        title: '<i class="fa-solid fa-users"></i> Danh sách Đảng viên - Chi bộ 3',
        members: [
            { name: 'Đ/c Phạm Long Châu', role: 'Phó Giám đốc', term: '2025 - 2027', avatar: 'Châu', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Trần Bửu Đức Quốc', role: 'Bí thư Chi bộ 3,  Đội Trưởng Đội Thi công tu bổ', term: '2025 - 2027', avatar: 'Quốc', color: 'var(--party-red)', roleColor: 'var(--party-red)', avatarBg: 'da3633' },
            { name: 'Đ/c Nguyễn Roãn Thạch', role: 'Đội Phó Đội Thi công tu bổ', term: '2025 - 2027', avatar: 'Thạch', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Lê Thanh Long', role: 'Đội Thi công tu bổ', term: '2025 - 2027', avatar: 'Long', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Tạ Quang', role: 'Đội Thi công tu bổ', term: '2025 - 2027', avatar: 'Quang', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Hoài Phúc', role: 'Đội Thi công tu bổ', term: '2025 - 2027', avatar: 'Phúc', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Trịnh Hồng Phát', role: 'Đội Thi công tu bổ', term: '2025 - 2027', avatar: 'Phát', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Hàng Phương Duy', role: 'Phó bí thư Chi bộ 3 Trưởng Phòng Giảm nước không doanh thu', term: '2025 - 2027', avatar: 'Duy', color: 'var(--party-red)', roleColor: 'var(--party-red)', avatarBg: 'da3633' },
            { name: 'Đ/c Lý Thanh Toàn', role: 'Phó Trưởng P Giàm nước không doanh thu', term: '2025 - 2027', avatar: 'Toàn', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Hữu Trung', role: 'Phòng Giàm nước không doanh thu', term: '2025 - 2027', avatar: 'Trung', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Tấn Tài', role: 'Phòng Giàm nước không doanh thu', term: '2025 - 2027', avatar: 'Tài', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Huỳnh Thị Thanh Hương', role: 'Chi ủy viên Chi bộ 3 Phòng Giàm nước không doanh thu', term: '2025 - 2027', avatar: 'Hương', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Lê Thành Nghĩa', role: 'Phòng Giàm nước không doanh thu', term: '2025 - 2027', avatar: 'Nghĩa', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
        ]
    },
    'chibo4': {
        title: '<i class="fa-solid fa-users"></i> Danh sách Đảng viên - Chi bộ 4',
        members: [
            { name: 'Đ/c Phạm Thanh Tuấn', role: 'Bí thư Chi bộ 1,  Trưởng Phòng Kiểm tra kiểm soát', term: '2025 - 2027', avatar: 'Tuấn', color: 'var(--party-red)', roleColor: 'var(--party-red)', avatarBg: 'da3633' },
            { name: 'Đ/c Nguyễn Hoàng Minh', role: 'ĐUV, Bí thư Chi bộ 4,  Trưởng phòng Dịch vụ khách hàng', term: '2025 - 2027', avatar: 'Minh', color: 'var(--party-red)', roleColor: 'var(--party-red)', avatarBg: 'da3633' },
            { name: 'Đ/c Trần Thị Kim Ngân', role: 'Chi ủy viên chi bộ 4 Phó Trưởng phòng DVKH', term: '2025 - 2027', avatar: 'Ngân', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Gia Quang Minh', role: 'Phó Trưởng phòng Dịch vụ khách hàng', term: '2025 - 2027', avatar: 'Minh', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Thị Gái Bảy', role: 'Phó Trưởng phòng Dịch vụ khách hàng', term: '2025 - 2027', avatar: 'Bảy', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Thị Ngọc Diệu', role: 'Phòng Dịch vụ khách hàng', term: '2025 - 2027', avatar: 'Diệu', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Huỳnh Hữu Thảo', role: 'Phòng Dịch vụ khách hàng', term: '2025 - 2027', avatar: 'Thảo', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Diệp Thị Vân Thanh', role: 'Phòng Dịch vụ khách hàng', term: '2025 - 2027', avatar: 'Thanh', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Đại Hoàng Quý', role: 'Phòng Dịch vụ khách hàng', term: '2025 - 2027', avatar: 'Quý', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Thị Thảo Vi', role: 'Phòng Dịch vụ khách hàng', term: '2025 - 2027', avatar: 'Vi', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Phan Nhật Huy', role: 'Phòng Dịch vụ khách hàng', term: '2025 - 2027', avatar: 'Huy', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Thị Hồng Đào', role: 'Phòng Dịch vụ khách hàng', term: '2025 - 2027', avatar: 'Đào', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Huỳnh Ngọc Hiền', role: 'Phòng Dịch vụ khách hàng', term: '2025 - 2027', avatar: 'Hiền', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Huỳnh Thị Xuân Quyên', role: 'Phòng Dịch vụ khách hàng', term: '2025 - 2027', avatar: 'Quyên', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Ngụy Kim Bích Nga', role: 'Phòng Dịch vụ khách hàng', term: '2025 - 2027', avatar: 'Nga', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Ngô Thụy Bích Thùy', role: 'Phòng Dịch vụ khách hàng', term: '2025 - 2027', avatar: 'Thùy', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Lê Trọng Phúc', role: 'Phó Trưởng phòng Kiểm tra kiểm soát', term: '2025 - 2027', avatar: 'Phúc', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Lê Hải Nam', role: 'Phòng Kiểm tra kiểm soát', term: '2025 - 2027', avatar: 'Nam', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Lưu Quới Thành', role: 'Phó Trưởng phòng Kiểm tra kiểm soát', term: '2025 - 2027', avatar: 'Thành', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Huỳnh Văn Chiến', role: 'Phòng Kiểm tra kiểm soát', term: '2025 - 2027', avatar: 'Chiến', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Thành Nhân', role: 'Phòng Kiểm tra kiểm soát', term: '2025 - 2027', avatar: 'Nhân', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Sơn Khoa', role: 'Phòng Kiểm tra kiểm soát', term: '2025 - 2027', avatar: 'Khoa', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Lã Thị Bích Thủy', role: 'Phòng Kiểm tra kiểm soát', term: '2025 - 2027', avatar: 'Thủy', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Đoàn Minh Ngọc', role: 'Phòng Kiểm tra kiểm soát', term: '2025 - 2027', avatar: 'Ngọc', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Phạm Thị Kim Dung', role: 'Phòng Kiểm tra kiểm soát', term: '2025 - 2027', avatar: 'Dung', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Bùi Thanh Phong', role: 'Phòng Kiểm tra kiểm soát', term: '2025 - 2027', avatar: 'Phong', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
        ]
    },
    'chibo5': {
        title: '<i class="fa-solid fa-users"></i> Danh sách Đảng viên - Chi bộ 5',
        members: [
            { name: 'Đ/c Nguyễn Minh Hải', role: 'ĐUV, Phó Giám đốc', term: '2025 - 2027', avatar: 'Hải', color: 'transparent', roleColor: 'var(--status-info)', avatarBg: '2f81f7' },
            { name: 'Đ/c Lê Anh Dũng', role: 'Bí thư Chi bộ 5,  Trưởng phòng Quản lý khách hàng 1', term: '2025 - 2027', avatar: 'Dũng', color: 'var(--party-red)', roleColor: 'var(--party-red)', avatarBg: 'da3633' },
            { name: 'Đ/c Chu Thế Hùng', role: 'ĐUV,Phó Bí thư Chi bộ 5 Trưởng phòng Quản lý khách hàng 2', term: '2025 - 2027', avatar: 'Hùng', color: 'var(--party-red)', roleColor: 'var(--party-red)', avatarBg: 'da3633' },
            { name: 'Đ/c Hoàng Lữ Huy Minh', role: 'Phó Trưởng phòng Quản lý khách hàng 1', term: '2025 - 2027', avatar: 'Minh', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Đặng Minh Hoàng', role: 'Phòng Quản lý khách hàng 1', term: '2025 - 2027', avatar: 'Hoàng', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Duy Tân', role: 'Phòng Quản lý khách hàng 1', term: '2025 - 2027', avatar: 'Tân', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Phạm Hải Tân', role: 'Phòng Quản lý khách hàng 1', term: '2025 - 2027', avatar: 'Tân', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Trần Hữu Quí', role: 'Phòng Quản lý khách hàng 1', term: '2025 - 2027', avatar: 'Quí', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Chính Trực', role: 'Phòng Quản lý khách hàng 1', term: '2025 - 2027', avatar: 'Trực', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Thị Tú Chinh', role: 'Phòng Quản lý khách hàng 1', term: '2025 - 2027', avatar: 'Chinh', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Đỗ Nguyễn Văn Thanh', role: 'Phòng Quản lý khách hàng 1', term: '2025 - 2027', avatar: 'Thanh', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Phạm Đăng Khoa', role: 'Phòng Quản lý khách hàng 1', term: '2025 - 2027', avatar: 'Khoa', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Thế Trí', role: 'Phòng Quản lý khách hàng 1', term: '2025 - 2027', avatar: 'Trí', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Ngụy Kim Bích Thủy', role: 'Chi ủy viên Chi bộ 5 Phó Trưởng Phòng Quản lý khách hàng 2', term: '2025 - 2027', avatar: 'Thủy', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Lê Bá Dược', role: 'Phòng Quản lý khách hàng 2', term: '2025 - 2027', avatar: 'Dược', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Phạm Thanh Tùng', role: 'Phòng Quản lý khách hàng 3', term: '2025 - 2027', avatar: 'Tùng', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Đăng Khoa', role: 'Phòng Quản lý khách hàng 2', term: '2025 - 2027', avatar: 'Khoa', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Mai Thanh Tú', role: 'Phòng Quản lý khách hàng 2', term: '2025 - 2027', avatar: 'Tú', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Trần Thị Thanh Xuân', role: 'Phòng Quản lý khách hàng 2', term: '2025 - 2027', avatar: 'Xuân', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Nguyễn Quốc Thông', role: 'Phòng Quản lý khách hàng 2', term: '2025 - 2027', avatar: 'Thông', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Lê Ngọc Kim Nhân', role: 'Phòng Quản lý khách hàng 2', term: '2025 - 2027', avatar: 'Nhân', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
            { name: 'Đ/c Bùi Chí Trung', role: 'Phòng Quản lý khách hàng 1', term: '2025 - 2027', avatar: 'Trung', color: 'transparent', roleColor: 'var(--text-muted)', avatarBg: '9e9e9e' },
        ]
    },
    'bch': {
        title: '<i class="fa-solid fa-users-gear"></i> Quản lý Cán bộ Chủ chốt (BCH Đảng ủy)',
        members: [
            {
                        'name': 'Đ/c Phạm Chí Thiện',
                        'role': 'Bí thư Đảng ủy/Chủ tịch HĐQT',
                        'term': '2025 - 2030',
                        'avatar': 'Thiện',
                        'color': 'var(--party-red)',
                        'roleColor': 'var(--party-red)',
                        'avatarBg': 'da3633'
            },
            {
                        'name': 'Đ/c Trần Đức Hùng',
                        'role': 'ĐUV, Phó Bí thư Chi bộ 1 Kế Toán trưởng',
                        'term': '2025 - 2030',
                        'avatar': 'Hùng',
                        'color': 'var(--party-red)',
                        'roleColor': 'var(--party-red)',
                        'avatarBg': 'da3633'
            },
            {
                        'name': 'Đ/c Nguyễn Thanh Tâm',
                        'role': 'ĐUV, Phó Trưởng Phòng TC-HC',
                        'term': '2025 - 2030',
                        'avatar': 'Tâm',
                        'color': 'transparent',
                        'roleColor': 'var(--status-info)',
                        'avatarBg': '2f81f7'
            },
            {
                        'name': 'Đ/c Lê Trọng Hiếu',
                        'role': 'Phó Bí thư đảng ủy, Giám đốc',
                        'term': '2025 - 2030',
                        'avatar': 'Hiếu',
                        'color': 'var(--party-red)',
                        'roleColor': 'var(--party-red)',
                        'avatarBg': 'da3633'
            },
            {
                        'name': 'Đ/c Trần Duy Minh',
                        'role': 'ĐUV, Bí thư Chi bộ 2 Trưởng Phòng Kỹ thuật',
                        'term': '2025 - 2030',
                        'avatar': 'Minh',
                        'color': 'var(--party-red)',
                        'roleColor': 'var(--party-red)',
                        'avatarBg': 'da3633'
            },
            {
                        'name': 'Đ/c Nguyễn Thị Kim Yến',
                        'role': 'Phó Bí Thư Chi bộ 2 Phó Trưởng Phòng Kỹ thuật',
                        'term': '2025 - 2030',
                        'avatar': 'Yến',
                        'color': 'var(--party-red)',
                        'roleColor': 'var(--party-red)',
                        'avatarBg': 'da3633'
            },
            {
                        'name': 'Đ/c Nguyễn Hàng Phương Duy',
                        'role': 'Phó bí thư Chi bộ 3 Trưởng Phòng Giảm nước không doanh thu',
                        'term': '2025 - 2030',
                        'avatar': 'Duy',
                        'color': 'var(--party-red)',
                        'roleColor': 'var(--party-red)',
                        'avatarBg': 'da3633'
            },
            {
                        'name': 'Đ/c Nguyễn Hoàng Minh',
                        'role': 'ĐUV, Bí thư Chi bộ 4,  Trưởng phòng Dịch vụ khách hàng',
                        'term': '2025 - 2030',
                        'avatar': 'Minh',
                        'color': 'var(--party-red)',
                        'roleColor': 'var(--party-red)',
                        'avatarBg': 'da3633'
            },
            {
                        'name': 'Đ/c Nguyễn Minh Hải',
                        'role': 'ĐUV, Phó Giám đốc',
                        'term': '2025 - 2030',
                        'avatar': 'Hải',
                        'color': 'transparent',
                        'roleColor': 'var(--status-info)',
                        'avatarBg': '2f81f7'
            },
            {
                        'name': 'Đ/c Chu Thế Hùng',
                        'role': 'ĐUV,Phó Bí thư Chi bộ 5 Trưởng phòng Quản lý khách hàng 2',
                        'term': '2025 - 2030',
                        'avatar': 'Hùng',
                        'color': 'var(--party-red)',
                        'roleColor': 'var(--party-red)',
                        'avatarBg': 'da3633'
            }
]
    }
};
