window.CONG_VAN_DATA = {
  "fetchTime": "09:42:39 14/4/2026",
  "totalDocs": 1,
  "soQuaHan": 0,
  "soGanHan": 0,
  "soChuaXem": 48,
  "docs": [
    {
      "soHieu": "466-CV/ĐU",
      "loai": "Công Văn",
      "trichYeu": "Về tuyên truyền Kỷ niệm 120 năm Ngày sinh Đồng chí Hà Huy Tập (24/4/1906 - 24/4/2026)",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "13/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/d1a441f1-975a-4153-9161-fda6991b06ee",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "462-CV/ĐU",
      "loai": "Công Văn",
      "trichYeu": "Về gửi Thông báo nhanh kết quả Hội nghị lần thứ hai Ban Chấp hành Trung ương Đảng khóa XIV",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "08/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/16843fc2-f8e9-4246-bf9a-6c496ef36760",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "39-BC/ĐU",
      "loai": "Báo Cáo",
      "trichYeu": "Báo cáo quản lý tài chính Đảng năm 2025",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "08/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/6924c7bf-393e-4106-8cb0-4817eec07050",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "79-TB/ĐU",
      "loai": "Thông Báo",
      "trichYeu": "Thông báo một số quyết định về công tác tổ chức - cán bộ Quý I năm 2026",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "08/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/988122af-5579-4457-9936-aa08265a2bde",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "190-QĐ/ĐU",
      "loai": "Quyết Định",
      "trichYeu": "Quyết định thành lập Chi bộ 5 trực thuộc Đảng bộ Công ty Cổ phần Cấp nước Trung An",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "08/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/939890bf-ab5d-4ccd-96dc-ad038cec3b80",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "189-QĐ/ĐU",
      "loai": "Quyết Định",
      "trichYeu": "Quyết định thành lập Chi bộ 4 trực thuộc Đảng bộ Công ty Cổ phần Cấp nước Trung An",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "08/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/58d183c6-c84a-4001-829e-a5fa559c4621",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "188-QĐ/ĐU",
      "loai": "Quyết Định",
      "trichYeu": "Quyết định thành lập Chi bộ 3 trực thuộc Đảng bộ Công ty Cổ phần Cấp nước Trung An",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "08/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/6176aa38-5305-4f4c-abf6-e79cce334a80",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "187-QĐ/ĐU",
      "loai": "Quyết Định",
      "trichYeu": "Quyết định thành lập Chi bộ 2 trực thuộc Đảng bộ Công ty Cổ phần Cấp nước Trung An",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "08/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/9cbd1d1c-c306-4608-8d6d-a4cbf58e530c",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "186-QĐ/ĐU",
      "loai": "Quyết Định",
      "trichYeu": "Quyết định thành lập Chi bộ 1 trực thuộc Đảng bộ Công ty Cổ phần Cấp nước Trung An",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "08/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/7436fa31-52d0-45a6-8e1b-18ac2f116338",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "185-QĐ/ĐU",
      "loai": "Quyết Định",
      "trichYeu": "Quyết định giải thể Chi bộ 1, 2, 3, 4, 5, 6 trực thuộc Đảng bộ Công ty Cổ phần Cấp nước Trung An",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "08/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/27a2ef07-2032-4c02-9e6c-5d93ee1ce10a",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "460-CV/ĐU",
      "loai": "Công Văn",
      "trichYeu": "Về xử lý tài chính đảng và một số nội dung sau khi thực hiện sắp xếp lại mô hình tổ chức đảng",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "08/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/cb87a057-bb5e-4af4-95f3-680957485a7d",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "459-CV/ĐU",
      "loai": "Công Văn",
      "trichYeu": "Về phổ biến, học tập các Chương trình hành động của Đảng ủy Ủy ban nhân dân Thành phố",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "08/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/6cb64239-dd73-43a4-a7e6-68a4de84c019",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "454-BC/ĐU",
      "loai": "Báo Cáo",
      "trichYeu": "Về rà soát, đăng ký danh sách đảng viên là công nhân trực tiếp sản xuất đủ điều kiện đề nghị tổ chức kết nạp Đảng tại đặc khu Côn Đảo theo chủ trương của Liên đoàn Lao động Thành phố Hồ Chí Minh",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "06/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/af359ed3-0490-4416-a72f-eb3d307d5a0a",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "44-BC/ĐU",
      "loai": "Báo Cáo",
      "trichYeu": "Báo cáo tình hình, kết quả triển khai thực hiện nhiệm vụ quý I, phương hướng nhiệm vụ trọng tâm quý II năm 2026",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "02/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/02ff7242-1198-4157-9b5f-be73648b2e69",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "04-BC/BCĐ",
      "loai": "Báo Cáo",
      "trichYeu": "Báo cáo Sơ kết, đánh giá kết quả thực hiện chương trình hành động số 07-CTr/ĐU ngày 05/09/2025 của Đảng ủy Tcty về thực hiện Nghị quyết Đại hội Đảng bộ Tcty Cấp nước Sài Gòn - TNHH MTV lần thứ V, nhiệm kỳ 2025 - 2030 về \"Phát triển hoàn thiện hệ thống cấp nước giai đoạn 2025 - 2030\"",
      "noiGui": "BAN CHỈ ĐẠO CHƯƠNG TRÌNH 07-CTR/ĐU",
      "ngayDen": "01/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/b38473f8-e5cf-4ee4-88df-561975d92d99",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "03-BC/BCĐ",
      "loai": "Báo Cáo",
      "trichYeu": "Báo cáo Sơ kết, đánh giá kết quả thực hiện chương trình hành động số 06-CTr/ĐU ngày 05/09/2025 của Đảng Ủy Tcty Cấp nước Sài Gòn về \"Đảm bảo an ninh, an toàn cấp nước, sẵn sàng ứng phó biến đổi khí hậu, ô nhiễm môi trường, nguồn nước\"",
      "noiGui": "BAN CHỈ ĐẠO CHƯƠNG TRÌNH 06-CTR/ĐU",
      "ngayDen": "01/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/38af9f69-3f40-4e58-acb2-a00abb0b0321",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "02-BC/BCĐ",
      "loai": "Báo Cáo",
      "trichYeu": "Báo cáo Sơ kết, đánh giá kết quả thực hiện chương trình hành động số 08-CTr/ĐU ngày 05/09/2025 của ĐU Tcty về \"Chuyển đổi số mạnh mẽ hoạt động cấp nước thành phố, nâng cao năng lực quản trị, quản lý kỹ thuật, xây dựng hệ thống cấp nước thông minh\"",
      "noiGui": "BAN CHỈ ĐẠO CHƯƠNG TRÌNH 08-CTR/ĐU",
      "ngayDen": "01/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/db6b4a40-6543-49f7-adb1-7ef90ae34215",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "01-BC/BCĐ",
      "loai": "Báo Cáo",
      "trichYeu": "Báo cáo Sơ kết, đánh giá kết quả thực hiện chương trình hành động số 04-CTr/ĐU ngày 24/07/2025 của ĐU Tổng Công ty v/v thực hiện Nghị Quyết số 57-NQ/TW ngày 22/12/2024 của Bộ Chính trị về đột phá phát triển khoa học, công nghệ, đổi mới sáng tạo và chuyển đổi số quốc gia",
      "noiGui": "BAN CHỈ ĐẠO CHƯƠNG TRÌNH 04-CTR/ĐU",
      "ngayDen": "01/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/2aec9197-f357-4dba-b056-ae9a3ef97f87",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "15-KH/ĐU",
      "loai": "Kế Hoạch",
      "trichYeu": "Kế hoạch tổ chức thi đua văn phòng cấp ủy năm 2026",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "30/03/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/3e7656ae-d6ed-4bdb-b463-19ac7ccb2be0",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "16-CTr/ĐU",
      "loai": "CHƯƠNG TRÌNH",
      "trichYeu": "Chương trình hành động thực hiện Nghị quyết Đại hội đại biểu toàn quốc lần thứ XIV của Đảng",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "30/03/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/3921c15e-3f8b-4ceb-98fb-a7c0c3c51a1e",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "91-NQ/ĐU",
      "loai": "Nghị Quyết",
      "trichYeu": "Nghị quyết về tăng cường lãnh đạo, chỉ đạo công tác hoàn chỉnh hồ sơ pháp lý, thực hiện nghĩa vụ tài chính và nâng cao hiệu quả quản lý, sử dụng các địa chỉ nhà, đất của Tổng Công ty Cấp nước Sài Gòn - TNHH MTV",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "30/03/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/54c410b5-0d4b-4374-b472-7ac914d22dee",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "90-NQ/ĐU",
      "loai": "Nghị Quyết",
      "trichYeu": "Nghị quyết Hội nghị Ban Chấp hành Đảng bộ Tổng Công ty lần thứ 10 - khóa V, nhiệm kỳ 2025 - 2030",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "30/03/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/7677cc84-f36f-4e37-a4db-4016a5c5b0d7",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "127-TB/ĐU",
      "loai": "Thông Báo",
      "trichYeu": "Thông báo Kết luận của BTV Đảng ủy về đánh giá, xếp loại chất lượng tổ chức đảng, tập thể cấp ủy và đảng viên năm 2025 đối với Cấp ủy và Đảng bộ TCT Cấp nước Sài Gòn",
      "noiGui": "ĐẢNG ỦY UBND TP",
      "ngayDen": "27/03/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/3f99b365-efd7-4fd0-99da-0fda3b5216cc",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "43-BC/ĐU",
      "loai": "Báo Cáo",
      "trichYeu": "Báo cáo Tổng kết đánh giá tình hình thực hiện Nghị quyết số 31-NQ/TW ngày 30 tháng 12 năm 2022 của Bộ Chính trị về phương hướng, nhiệm vụ phát triển Thành phố Hồ Chí Minh đến năm 2030, tầm nhìn đến năm 2045",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "25/03/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/4e201c36-d532-46e0-9d9c-f125acad22c5",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "466-CV/ĐU",
      "loai": "Công Văn",
      "trichYeu": "Về tuyên truyền Kỷ niệm 120 năm Ngày sinh Đồng chí Hà Huy Tập (24/4/1906 - 24/4/2026)",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "13/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/d1a441f1-975a-4153-9161-fda6991b06ee",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "462-CV/ĐU",
      "loai": "Công Văn",
      "trichYeu": "Về gửi Thông báo nhanh kết quả Hội nghị lần thứ hai Ban Chấp hành Trung ương Đảng khóa XIV",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "08/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/16843fc2-f8e9-4246-bf9a-6c496ef36760",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "39-BC/ĐU",
      "loai": "Báo Cáo",
      "trichYeu": "Báo cáo quản lý tài chính Đảng năm 2025",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "08/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/6924c7bf-393e-4106-8cb0-4817eec07050",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "79-TB/ĐU",
      "loai": "Thông Báo",
      "trichYeu": "Thông báo một số quyết định về công tác tổ chức - cán bộ Quý I năm 2026",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "08/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/988122af-5579-4457-9936-aa08265a2bde",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "190-QĐ/ĐU",
      "loai": "Quyết Định",
      "trichYeu": "Quyết định thành lập Chi bộ 5 trực thuộc Đảng bộ Công ty Cổ phần Cấp nước Trung An",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "08/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/939890bf-ab5d-4ccd-96dc-ad038cec3b80",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "189-QĐ/ĐU",
      "loai": "Quyết Định",
      "trichYeu": "Quyết định thành lập Chi bộ 4 trực thuộc Đảng bộ Công ty Cổ phần Cấp nước Trung An",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "08/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/58d183c6-c84a-4001-829e-a5fa559c4621",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "188-QĐ/ĐU",
      "loai": "Quyết Định",
      "trichYeu": "Quyết định thành lập Chi bộ 3 trực thuộc Đảng bộ Công ty Cổ phần Cấp nước Trung An",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "08/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/6176aa38-5305-4f4c-abf6-e79cce334a80",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "187-QĐ/ĐU",
      "loai": "Quyết Định",
      "trichYeu": "Quyết định thành lập Chi bộ 2 trực thuộc Đảng bộ Công ty Cổ phần Cấp nước Trung An",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "08/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/9cbd1d1c-c306-4608-8d6d-a4cbf58e530c",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "186-QĐ/ĐU",
      "loai": "Quyết Định",
      "trichYeu": "Quyết định thành lập Chi bộ 1 trực thuộc Đảng bộ Công ty Cổ phần Cấp nước Trung An",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "08/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/7436fa31-52d0-45a6-8e1b-18ac2f116338",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "185-QĐ/ĐU",
      "loai": "Quyết Định",
      "trichYeu": "Quyết định giải thể Chi bộ 1, 2, 3, 4, 5, 6 trực thuộc Đảng bộ Công ty Cổ phần Cấp nước Trung An",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "08/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/27a2ef07-2032-4c02-9e6c-5d93ee1ce10a",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "460-CV/ĐU",
      "loai": "Công Văn",
      "trichYeu": "Về xử lý tài chính đảng và một số nội dung sau khi thực hiện sắp xếp lại mô hình tổ chức đảng",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "08/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/cb87a057-bb5e-4af4-95f3-680957485a7d",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "459-CV/ĐU",
      "loai": "Công Văn",
      "trichYeu": "Về phổ biến, học tập các Chương trình hành động của Đảng ủy Ủy ban nhân dân Thành phố",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "08/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/6cb64239-dd73-43a4-a7e6-68a4de84c019",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "454-BC/ĐU",
      "loai": "Báo Cáo",
      "trichYeu": "Về rà soát, đăng ký danh sách đảng viên là công nhân trực tiếp sản xuất đủ điều kiện đề nghị tổ chức kết nạp Đảng tại đặc khu Côn Đảo theo chủ trương của Liên đoàn Lao động Thành phố Hồ Chí Minh",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "06/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/af359ed3-0490-4416-a72f-eb3d307d5a0a",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "44-BC/ĐU",
      "loai": "Báo Cáo",
      "trichYeu": "Báo cáo tình hình, kết quả triển khai thực hiện nhiệm vụ quý I, phương hướng nhiệm vụ trọng tâm quý II năm 2026",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "02/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/02ff7242-1198-4157-9b5f-be73648b2e69",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "04-BC/BCĐ",
      "loai": "Báo Cáo",
      "trichYeu": "Báo cáo Sơ kết, đánh giá kết quả thực hiện chương trình hành động số 07-CTr/ĐU ngày 05/09/2025 của Đảng ủy Tcty về thực hiện Nghị quyết Đại hội Đảng bộ Tcty Cấp nước Sài Gòn - TNHH MTV lần thứ V, nhiệm kỳ 2025 - 2030 về \"Phát triển hoàn thiện hệ thống cấp nước giai đoạn 2025 - 2030\"",
      "noiGui": "BAN CHỈ ĐẠO CHƯƠNG TRÌNH 07-CTR/ĐU",
      "ngayDen": "01/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/b38473f8-e5cf-4ee4-88df-561975d92d99",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "03-BC/BCĐ",
      "loai": "Báo Cáo",
      "trichYeu": "Báo cáo Sơ kết, đánh giá kết quả thực hiện chương trình hành động số 06-CTr/ĐU ngày 05/09/2025 của Đảng Ủy Tcty Cấp nước Sài Gòn về \"Đảm bảo an ninh, an toàn cấp nước, sẵn sàng ứng phó biến đổi khí hậu, ô nhiễm môi trường, nguồn nước\"",
      "noiGui": "BAN CHỈ ĐẠO CHƯƠNG TRÌNH 06-CTR/ĐU",
      "ngayDen": "01/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/38af9f69-3f40-4e58-acb2-a00abb0b0321",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "02-BC/BCĐ",
      "loai": "Báo Cáo",
      "trichYeu": "Báo cáo Sơ kết, đánh giá kết quả thực hiện chương trình hành động số 08-CTr/ĐU ngày 05/09/2025 của ĐU Tcty về \"Chuyển đổi số mạnh mẽ hoạt động cấp nước thành phố, nâng cao năng lực quản trị, quản lý kỹ thuật, xây dựng hệ thống cấp nước thông minh\"",
      "noiGui": "BAN CHỈ ĐẠO CHƯƠNG TRÌNH 08-CTR/ĐU",
      "ngayDen": "01/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/db6b4a40-6543-49f7-adb1-7ef90ae34215",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "01-BC/BCĐ",
      "loai": "Báo Cáo",
      "trichYeu": "Báo cáo Sơ kết, đánh giá kết quả thực hiện chương trình hành động số 04-CTr/ĐU ngày 24/07/2025 của ĐU Tổng Công ty v/v thực hiện Nghị Quyết số 57-NQ/TW ngày 22/12/2024 của Bộ Chính trị về đột phá phát triển khoa học, công nghệ, đổi mới sáng tạo và chuyển đổi số quốc gia",
      "noiGui": "BAN CHỈ ĐẠO CHƯƠNG TRÌNH 04-CTR/ĐU",
      "ngayDen": "01/04/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/2aec9197-f357-4dba-b056-ae9a3ef97f87",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "15-KH/ĐU",
      "loai": "Kế Hoạch",
      "trichYeu": "Kế hoạch tổ chức thi đua văn phòng cấp ủy năm 2026",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "30/03/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/3e7656ae-d6ed-4bdb-b463-19ac7ccb2be0",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "16-CTr/ĐU",
      "loai": "CHƯƠNG TRÌNH",
      "trichYeu": "Chương trình hành động thực hiện Nghị quyết Đại hội đại biểu toàn quốc lần thứ XIV của Đảng",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "30/03/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/3921c15e-3f8b-4ceb-98fb-a7c0c3c51a1e",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "91-NQ/ĐU",
      "loai": "Nghị Quyết",
      "trichYeu": "Nghị quyết về tăng cường lãnh đạo, chỉ đạo công tác hoàn chỉnh hồ sơ pháp lý, thực hiện nghĩa vụ tài chính và nâng cao hiệu quả quản lý, sử dụng các địa chỉ nhà, đất của Tổng Công ty Cấp nước Sài Gòn - TNHH MTV",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "30/03/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/54c410b5-0d4b-4374-b472-7ac914d22dee",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "90-NQ/ĐU",
      "loai": "Nghị Quyết",
      "trichYeu": "Nghị quyết Hội nghị Ban Chấp hành Đảng bộ Tổng Công ty lần thứ 10 - khóa V, nhiệm kỳ 2025 - 2030",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "30/03/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/7677cc84-f36f-4e37-a4db-4016a5c5b0d7",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "127-TB/ĐU",
      "loai": "Thông Báo",
      "trichYeu": "Thông báo Kết luận của BTV Đảng ủy về đánh giá, xếp loại chất lượng tổ chức đảng, tập thể cấp ủy và đảng viên năm 2025 đối với Cấp ủy và Đảng bộ TCT Cấp nước Sài Gòn",
      "noiGui": "ĐẢNG ỦY UBND TP",
      "ngayDen": "27/03/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/3f99b365-efd7-4fd0-99da-0fda3b5216cc",
      "status": "chua_xem",
      "daysLeft": null
    },
    {
      "soHieu": "43-BC/ĐU",
      "loai": "Báo Cáo",
      "trichYeu": "Báo cáo Tổng kết đánh giá tình hình thực hiện Nghị quyết số 31-NQ/TW ngày 30 tháng 12 năm 2022 của Bộ Chính trị về phương hướng, nhiệm vụ phát triển Thành phố Hồ Chí Minh đến năm 2030, tầm nhìn đến năm 2045",
      "noiGui": "ĐẢNG ỦY TỔNG CÔNG TY",
      "ngayDen": "25/03/2026",
      "hanXuLy": "",
      "link": "https://vpdt.capnuoctrungan.vn/CongVan/ChiTietCongVan/4e201c36-d532-46e0-9d9c-f125acad22c5",
      "status": "chua_xem",
      "daysLeft": null
    }
  ]
};